syntax on
filetype on
set nocp nu ru bs=2 bg=dark ai si cin fo+=ro ts=2 sw=2 sts=2 et is nohls mouse=a aw ar wmnu nowrap noswf nobackup
map <F3> :s!^!//!<CR>
map <F4> :s!^//!!<CR>
map <C-h> gT
map <C-l> gt
